name: Christian Gregson BSP Design
favicon: null
layout_spectrum: 0.13884187396615744
typography_spectrum: 0.58971
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3125
  lightness: 0.9572748923674226
  saturation: 0.12230119318701327
  rhythmicContrast: 0.040090375347062945
purpose: []
